name: Garcias Luthier
favicon: null
layout_spectrum: 0.5084177772514522
typography_spectrum: 0.6761818728409708
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6288230812642723
  lightness: 0.7150253159925342
  saturation: 0.8320841426029801
  rhythmicContrast: 0.5454975280445069
purpose: []
